version: '3.7'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      - ./:/usr/src/app 
    working_dir: /usr/src/app 
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!
