version: '2'

services:
  # Producer
  ms-producer:
    image: ms-producer:latest
    ports:
      - 12140:80
    depends_on:
      - mongo
      - kafka
    restart: always
    container_name: ms-producer
    networks:
      - net-kafka
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ms-producer
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - net-kafka
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - net-kafka
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "8888:8081"
  # Consumer
  ms-consumer:
    image: ms-consumer:latest
    ports:
      - 12141:80
    depends_on:
      - kafka
    restart: always
    container_name: ms-consumer
    networks:
      - net-kafka
  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - net-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - net-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:

  net-kafka:
    driver: bridge
